config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show] do
    resources :items, only: [:create, :destroy]     
  end

  get 'welcome/index'

  get 'welcome/show'

  root 'users#show'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
        

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = current_user.items.new(item_params)

    if @item.save
      flash[:notice] = "Success!"
    else
      flash[:alert] = "Did not save!"
    end
    redirect_to root_path
  end

  def destroy
    @item = current_user.items.find(params[:id])
    if @item.destroy
      flash[:notice] = "Item was deleted"
    else
      flash.now[:alert] = "Item was not deleted properly"
    end
    respond_to do |format|
      format.html { redirect_to root_path}
      format.js
    end
  end


private
  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [current_user, Item.new] do |f| %>
  <%= f.label :name, "To-do" %>
  <%= f.text_field :name %>

  <%= f.submit "Save", class: "btn btn-success" %>
<% end %>

app/views/items/_item.html.erb
<tr id="item-<%= item.id %>">
  <td><%= item.name %></td>
  <td><%= distance_of_time_in_words(Time.now, item.created_at + 7.days) %> <%= item.created_at > Time.now - 7.days ? "overdue" : "left" %></td>
  <td><%= link_to "", user_item_path(current_user, item), method: :delete, remote: true, class: 'glyphicon glyphicon-ok' %></td>
</tr>

app/views/items/destroy.js.erb
$('#item-<%= @item.id %>').hide();
$('.flash').html('<div class="alert alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>Your item was deleted.</div>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocitoff", welcome_index_path %></li>
      <li><%= link_to "About", welcome_show_path %></li>
      <div class ='nav navbar-right'>
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
        <% end %>
      </div>
    </ul>
    
    <div class="flash">
        <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
        <% elsif flash.now[:alert] %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash.now[:alert] %>
          </div>
        <% elsif flash[:alert] %>
          <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>


    <%= yield %>

  </div>

</body>
</html>

app/views/users/show.html.erb
<h1>Hi, <%= current_user.email %>!</h1>

<h3>Add an item</h3>
<%= render partial: "items/form" %>

<table class="table table-striped table-hover">
  <tr>
    <th>Item</th>
    <th>Time remaining</th>
    <th></th>
  </tr>
  <%= render current_user.items %>
</table>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/show.html.erb
<h1>Welcome#show</h1>
<p>Find me in app/views/welcome/show.html.erb</p>